"""Bind the authored HTML report to measured study records, preserving its identity."""
from pathlib import Path
import json
import statistics
from datetime import datetime, timezone

ROOT = Path(__file__).resolve().parents[1]
REPO = "https://github.com/atilavahedian/cotangent"


def source(title, files, components, definitions, caveats=()):
    return {"title": title, "provider": "Cotangent local measured experiments",
            "files": files, "links": [{"label": "Inspect research evidence", "url": REPO + "/tree/main/artifacts"}],
            "metricDefinitions": [{"label": name, "definition": definition, "componentIds": components} for name, definition in definitions],
            "caveats": list(caveats), "evidenceFlow": [{"title": "Reproducible evidence", "detail": "Frozen protocol → raw per-run records → analysis/analyze.py → reviewed report snapshot. No missing target times are imputed."}]}


def main():
    path = ROOT / "report/src/data.json"
    snapshot = json.loads(path.read_text())
    snapshot.update({"title": "Cotangent", "generatedAt": datetime.now(timezone.utc).isoformat(),
                     "status": "observed-local-research", "buildStatus": "creating"})
    prose = {
        "deck": "Can we make backpropagation cheaper without making the model worse? A standalone experiment in adaptive, variance-aware weight-gradient sampling.",
        "findings": "## The final experiment is running\n\nThe frozen study contains 36 training runs. Diagnostic pilots have not demonstrated a speed advantage. Final results will replace this preliminary view when every planned arm and seed is complete.",
        "controller": "## Spend accuracy where the gradient needs it\n\nCotangent audits each selected layer every 32 steps. An exact weight gradient estimates signal strength; row norms estimate the sampling second moment. The controller chooses a row budget for the next interval, bounded below by 64 rows. If its requested budget reaches 75% of all rows, ordinary native backpropagation is used on non-audit steps.\n\nActivation gradients stay exact. Audit steps use exact weight gradients. The controller is a heuristic based on stale statistics; it does not certify the error of every intervening update.",
        "mathematics": "## The mathematical idea\n\nFor a linear layer, flatten the batch and sequence dimensions into N rows. Let X contain input activations and D contain output cotangents. The weight gradient is a sum of rank-one matrices:\n\n`G = DᵀX = Σᵢ dᵢ xᵢᵀ`.\n\nDraw k rows independently with replacement from probabilities pᵢ, then use\n\n`Ĝ = (1/k) Σⱼ (dᵢⱼ xᵢⱼᵀ / pᵢⱼ)`.\n\nConditional on the model and batch, its expectation is the exact weight gradient before floating-point rounding. Its mean-squared Frobenius error is\n\n`E‖Ĝ − G‖² = (Σᵢ ‖dᵢ‖²‖xᵢ‖²/pᵢ − ‖G‖²) / k`.\n\nThe variance-minimizing probabilities are proportional to `‖dᵢ‖‖xᵢ‖`; a 5% uniform mixture prevents zero support. The audit uses this expression to estimate k for a relative RMS error target of 0.5. The exact input gradient remains `dX = DW`.\n\nThis applies classical [randomized matrix multiplication](https://doi.org/10.1137/S0097539704442684) to training; importance sampling itself is established prior art. The project contribution is the tested controller, backend implementation, matched comparisons, and preserved evidence.\n\nEven perfect removal of the weight-gradient multiplication leaves the forward and input-gradient multiplications. The arithmetic-only speed ceiling for that linear layer is 1.5×; attention, optimizer work, sampling, and audits reduce the end-to-end opportunity. Unbiased gradients do not imply unbiased AdamW updates after nonlinear clipping. [Full derivation and assumptions](https://github.com/atilavahedian/cotangent/blob/main/docs/MATHEMATICS.md).",
        "study-design": "## A frozen, matched comparison\n\nAll arms train the same byte-level causal transformer on [WikiText-2](https://huggingface.co/datasets/Salesforce/wikitext), starting from scratch. The main model has 3,346,944 parameters, four layers, width 256, sequence length 256, and batch size eight. Six methods run for 2,000 steps across paired seeds 11, 23, 37, 53, and 71. A 19,280,896-parameter, six-layer model compares native and adaptive backward for 1,500 steps across three paired seeds.\n\nNative BF16 exact backpropagation is the primary baseline. Controls include exact custom backward, uniform 25% row sampling, importance 25% sampling, and a 25% Walsh–Hadamard sequence projection. The projection control changes activation gradients as well as weight gradients; it is inspired by [LBP-WHT](https://arxiv.org/abs/2309.15275), not an official reproduction.\n\nInitialization, batch schedules, data, precision, AdamW settings, learning-rate schedules, and evaluation windows are matched. Every optimizer step synchronizes Metal. Elapsed time includes setup, data transfer, sampling, audits, clipping, optimization, resource checks, and validation probes.\n\nSuccess was defined before held-out evaluation: every primary pair must reach 3.2 validation bits per byte, mean paired time reduction must be at least 10% with its 95% interval above zero, and the upper paired interval for final test degradation must be at most 0.03 BPB. Time is recorded at the first scheduled crossing, without interpolation. [Inspect the frozen protocol](https://github.com/atilavahedian/cotangent/blob/main/artifacts/frozen-study.json).",
        "pilots": "## What changed during development\n\nOnly a held-out portion of the training split informed development. The first Metal optimizer attempt failed because forced foreach clipping was unsupported; that failure remains in the record. BF16 became the matched baseline after a precision pilot.\n\nThe initial adaptive implementation synchronized the CPU once per layer and was substantially slower. Batching audits into one transfer and bypassing sampling when the controller selected dense computation removed most of that overhead. The final source and protocol were frozen after these revisions. The table shows the revised one-seed diagnostic pilot, not final superiority evidence.",
        "limits": "## What this study can establish\n\nThis is a local experiment on one corpus and one Apple M5 Pro with 24 GiB of memory. It does not establish performance on CUDA, billion-parameter models, distributed training, or other tasks. Five primary seeds and three larger-model seeds provide limited statistical evidence, and serial desktop timing can vary with the environment.\n\nThe scheduled quality probes cover the first 65,536 validation bytes; the final validation and test evaluations cover their complete splits with fixed, non-overlapping contexts. Bits per byte is not directly comparable to word-token perplexity.\n\nThe method retains full activations and exact activation gradients, so it makes no activation-memory reduction claim. [INSTANT](https://github.com/hieu-trannn/INSTANT) targets gradient and activation compression; [APOLLO](https://arxiv.org/abs/2412.05270) targets optimizer-state memory. Neither is directly reproduced here, so this report cannot claim to beat those methods.",
        "reproduce": "## Inspect and reproduce\n\nThe [public repository](https://github.com/atilavahedian/cotangent) contains newly written research code, mathematical notes, tests, diagnostic failures, the frozen protocol, raw JSONL curves, and per-run summaries. Commits record protocol design, implementation, development measurements, optimization, and the freeze as separate milestones.\n\nNo code, trained weights, data preparations, or results were inherited from the author's previous projects. Training used local hardware only. The report interface uses the general-purpose Data runtime.\n\nFollow the repository instructions to download the pinned dataset, verify the derivatives, rerun the frozen campaign, and recompute its conclusions. Dataset content is not redistributed; its source license remains separate from the MIT research implementation."
    }
    result_path = ROOT / "artifacts/analysis/results.json"
    if result_path.exists():
        r = json.loads(result_path.read_text())
        p, m = r["primary"], r["medium"]
        q, t = p["quality_difference_bpb"], p["elapsed_reduction_fraction"]
        verdict = "Cotangent met the frozen success criteria" if p["success"] else "Cotangent did not beat the measured baseline"
        def fmt(ci, scale=1, digits=2):
            return f"{ci['mean']*scale:.{digits}f} (95% CI {ci['lower']*scale:.{digits}f} to {ci['upper']*scale:.{digits}f})"
        timing = f"**{fmt(t,100)}%**" if t else "**censored: at least one arm did not reach the target**"
        mean_fraction=statistics.mean(x["sample_fraction"] for x in r["sampling_observations"] if x["group"]=="small")
        prose["findings"] = f"## {verdict}\n\nAcross five paired seeds, Cotangent's mean elapsed time reduction to 3.2 validation BPB was {timing}. Positive means faster; negative means slower. The predeclared minimum was 10%, with an interval above zero.\n\nFinal test degradation was **{fmt(q,digits=4)} BPB**. The quality gate {'passed' if p['quality_gate_pass'] else 'failed'} against the 0.03-BPB margin. All primary pairs {'reached' if p['all_reached'] else 'did not reach'} the target. The combined efficiency-and-quality gate {'passed' if p['success'] else 'failed'}.\n\nAll **36 planned runs completed**, representing **141,312,000 predicted training bytes** across the campaign. The result applies to this measured setup, not to all existing backpropagation methods."
        prose["curves"] = "## Equal work does not guarantee equal learning\n\nEach point is the mean of five scheduled official-validation probes. These plots show the complete frozen training budget, including unsuccessful fixed compression controls. The time plot averages elapsed time and quality at corresponding optimizer steps; the primary effect estimate uses individual seed crossings in the table above, not crossings interpolated from these mean curves."
        prose["controller"] += f"\n\nAcross recorded training steps in the small-model arms, the mean layer row fraction was **{100*mean_fraction:.1f}%**. This is an unweighted diagnostic average at logging points, not a measured full-run FLOP reduction. Values of one include native fallbacks and exact audits. The behavior explains why quality preservation can leave little computation to save."
        mq, mt = m["quality_difference_bpb"], m["elapsed_reduction_fraction"]
        prose["limits"] += f"\n\nThe larger model's three-seed descriptive comparison showed **{fmt(mt,100)}%** time reduction and **{fmt(mq,digits=4)} BPB** final test difference." if mt else "\n\nThe larger-model time comparison contains censored crossings."
        prose["reproduce"] += "\n\nThe final integrity audit checked all 36 expected runs, matching paired initialization and batch schedules, frozen source and data-manifest hashes, full held-out evaluation coverage, raw-curve/summary consistency, and every checkpoint's SHA-256. These checks verify evidence consistency; they do not convert a failed efficiency gate into a success."
        queries = {
            "method_summary": (r["aggregates"], ["artifacts/analysis/method-means.csv"], ["method-table","limits"], [("Test BPB", "Mean full official-test cross entropy divided by ln(2); lower is better."), ("Time to target", "Mean elapsed time through the first scheduled 3.2-BPB crossing, only when all seeds reached; otherwise null and censored.")]),
            "paired_results": (p["pairs"]+m["pairs"], ["artifacts/analysis/paired-primary.csv","artifacts/analysis/results.json"], ["paired-table","findings"], [("Time reduction", "1 - adaptive elapsed crossing time / native elapsed crossing time, paired by seed; positive means faster."), ("Test difference", "Adaptive full-test BPB minus native full-test BPB, paired by seed; lower is better.")]),
            "learning_curves": (r["mean_learning_curves"], ["artifacts/final/*/*/curve.jsonl"], ["quality-curve","elapsed-curve","curves"], [("Validation BPB", "Arithmetic mean of corresponding-step probes across five small or three medium paired seeds; each probe contains 65,536 target bytes.")]),
            "sampling_curves": (r["sampling_observations"], ["artifacts/final/*/adaptive-*/curve.jsonl"], ["sample-curve","controller"], [("Sample fraction", "Unweighted mean of selected row fractions across layers at recorded training steps; 1 includes native fallback and exact audits. Not an arithmetic-weighted full-run quantity.")]),
            "integrity": ([{"runs":r["runs"],"predicted_training_bytes":r["predicted_training_bytes"],"source_sha256":r["frozen_source_sha256"],"paired_integrity":r["integrity_checks_passed"]}], ["artifacts/analysis/results.json","artifacts/frozen-study.json","artifacts/verification-mps.json"], ["mathematics","study-design","reproduce"], [("Integrity audit", "Analysis validates the planned set, statuses, source/data hashes, paired initialization and schedules, evaluation coverage and checkpoint file hashes.")]),
        }
        for key,(rows,files,ids,defs) in queries.items():
            snapshot["queries"][key] = {"rows":rows,"source":source(key.replace("_"," ").title(), files, ids, defs, r["limitations"])}
        snapshot["buildStatus"]="complete"
    snapshot["report"] = {"asOf":"2026-10-03", "narratives":prose}
    path.write_text(json.dumps(snapshot,indent=2)+"\n")
    print(json.dumps({"id":snapshot["id"],"queries":list(snapshot["queries"]),"buildStatus":snapshot["buildStatus"]}))


if __name__=="__main__":
    main()
